### ISSUE TITLE
Build i686-pc-windows-msvc use wintun.dll 64bit

### ISSUE THREAD

**Issue by ngochoaitn** [blechschmidt/tun2proxy#101]
When use command build:
`cargo build --release --target i686-pc-windows-msvc`
output folder use wintun.dll of 64bit (in public release build v0.2.12 same issue)

**Comment by ssrlive** [comment]
what size of your `wintun.dll` file?

![image](https://github.com/blechschmidt/tun2proxy/assets/30760636/1b4270f1-0736-41dc-869c-d3ecedb81671)
