### ISSUE TITLE
Add documentation for android please

### ISSUE THREAD

**Issue by dimaslanjaka** [blechschmidt/tun2proxy#102]
I want build this for android, what should i do ?

**Comment by ssrlive** [comment]
You must modify the signatures of these two functions to suit your project, and then compile it into a .so file. Then you can use tun2proxy in your project.

`Java_com_github_shadowsocks_bg_Tun2proxy_run` 

`Java_com_github_shadowsocks_bg_Tun2proxy_stop`

https://github.com/blechschmidt/tun2proxy/blob/a1083273ee125c28f5e9f2252b46cf9105888004/src/android.rs#L18-L26

https://github.com/blechschmidt/tun2proxy/blob/a1083273ee125c28f5e9f2252b46cf9105888004/src/android.rs#L49

**Comment by dimaslanjaka** [comment]
hmm iam new for rust. can you provide rust doc above the function ? i dont know what values to be inserted into parameters. like `proxy_url` is value `0.0.0.0:80` or `socks://0.0.0.0:80`, and what values for other parameters in java/kotlin

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/ssrDroid/blob/fd6debb05560f7476325afacdd753faf5fde5e78/core/src/main/java/com/github/shadowsocks/bg/Tun2proxy.kt#L1-L13

**Comment by dimaslanjaka** [comment]
> https://github.com/ShadowsocksR-Live/ssrDroid/blob/fd6debb05560f7476325afacdd753faf5fde5e78/core/src/main/java/com/github/shadowsocks/bg/Tun2proxy.kt#L1-L13

add kotlin docs please. 

```kotlin
/**
   * @param proxyUrl IP:HOST or socks://IP:HOST ?
   * @param tunFd how much integer ?
   * @param tunMtu how much integer ?
   * @param verbosity how much integer ?
   * @param dnsStrategy how much integer ?
   */
  external fun run(proxyUrl: String, tunFd: Int, tunMtu: Char, verbosity: Int, dnsStrategy: Int): Int
  /**
   * @return 0=what for? 1=what for? and what other return value for ? 
   */
  external fun stop(): Int
```

**Comment by ssrlive** [comment]
add kotlin docs please. i dont know what values to pass into parameters

```kotlin
  /**
   * @param proxyUrl IP:HOST or socks://IP:port, such as socks5://127.0.0.1:1080
   * @param tunFd how much integer, it's provided by android, such as 5,
   * @param tunMtu what values, it's normally 1500,
   * @param verbosity how much integer, it can be 0 t0 5,
   * @param dnsStrategy how much integer, can set to 0 to 2, normally 2,
   * 
   * @return  0 is success, not 0 if failed.
   */
  external fun run(proxyUrl: String, tunFd: Int, tunMtu: Char, verbosity: Int, dnsStrategy: Int): Int
  /**
   * @return  0 is success, not 0 if failed.
   */
  external fun stop(): Int
```

**Comment by dimaslanjaka** [comment]
okay thanks

**Comment by ssrlive** [comment]
[wiki](https://github.com/tun2proxy/tun2proxy/wiki/Integrate-to-Android-platform)
