### ISSUE TITLE
got error while compiling 

### ISSUE THREAD

**Issue by mrwrenchy** [blechschmidt/tun2proxy#20]
root@server: cargo build --release
   Compiling tun2proxy v0.1.1 (/root/tun2proxy)
error[E0432]: unresolved import `std::os::fd::FromRawFd`
 --> src/setup.rs:7:5
  |
7 | use std::os::fd::FromRawFd;
  |     ^^^^^^^^^^^^^^^^^^^^^^ no `FromRawFd` in `os::fd`

error[E0603]: module `fd` is private
 --> src/setup.rs:7:14
  |
7 | use std::os::fd::FromRawFd;
  |              ^^ private module
  |
note: the module `fd` is defined here

error[E0599]: no function or associated item named `from_raw_fd` found for struct `File` in the current scope
   --> src/setup.rs:158:40
    |
158 |             let mut f = std::fs::File::from_raw_fd(fd);
    |                                        ^^^^^^^^^^^ function or associated item not found in `File`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use std::os::unix::io::FromRawFd;
    |

warning: unused import: `Write`
 --> src/setup.rs:4:24
  |
4 | use std::io::{BufRead, Write};
  |                        ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

Some errors have detailed explanations: E0432, E0599, E0603.
For more information about an error, try `rustc --explain E0432`.
warning: `tun2proxy` (lib) generated 1 warning
error: could not compile `tun2proxy` due to 3 previous errors; 1 warning emitted

**Comment by blechschmidt** [comment]
Which operating system? Could you please provide the output of `uname -a` and `cargo --version`, so I can try to reproduce this?

**Comment by anweshan1** [comment]
uname -a: Linux u1 5.4.0-1087-kvm #93-Ubuntu SMP Thu Feb 9 20:12:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
cargo --version: cargo 1.65.0
This is actually a LXC container where i was trying to compile the application, is that a problem?

**Comment by blechschmidt** [comment]
b8a08871d05bf4f2107fc4f5d4f1fe05c9e7cd06 fixes this.
