### ISSUE TITLE
support windows tun_wireguard_windows?

### ISSUE THREAD

**Issue by f4nff** [blechschmidt/tun2proxy#31]
support windows tun_wireguard_windows?

https://github.com/xjasonlyu/tun2socks/tree/main/core/device/tun

**Comment by f4nff** [comment]
Golang's program takes up too much memory, and rust performs very well.

**Comment by f4nff** [comment]
https://www.wintun.net/

**Comment by blechschmidt** [comment]
Since tun2proxy uses [smoltcp](https://github.com/smoltcp-rs/smoltcp), this would primarily depend on smoltcp supporting it.

**Comment by Morrigan-Ship** [comment]
how to use on windows
