### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by yangdehui** [blechschmidt/tun2proxy#34]
Compiling tun2proxy v0.1.1 (/Users/yangdehui/Desktop/ssrDroid/rust/tun2proxy)
error[E0432]: unresolved import `smoltcp::phy::TunTapInterface`
  --> tun2proxy/src/tun2proxy.rs:10:45
   |
10 | use smoltcp::phy::{Device, Medium, RxToken, TunTapInterface, TxToken};
   |                                             ^^^^^^^^^^^^^^^ no `TunTapInterface` in `phy`

warning: unused import: `std::os::unix::io::AsRawFd`
  --> tun2proxy/src/tun2proxy.rs:20:5
   |
20 | use std::os::unix::io::AsRawFd;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `Device`
  --> tun2proxy/src/tun2proxy.rs:10:20
   |
10 | use smoltcp::phy::{Device, Medium, RxToken, TunTapInterface, TxToken};
   |                    ^^^^^^

warning: unused import: `RxToken`
  --> tun2proxy/src/tun2proxy.rs:10:36
   |
10 | use smoltcp::phy::{Device, Medium, RxToken, TunTapInterface, TxToken};
   |                                    ^^^^^^^

warning: unused import: `TxToken`
  --> tun2proxy/src/tun2proxy.rs:10:62
   |
10 | use smoltcp::phy::{Device, Medium, RxToken, TunTapInterface, TxToken};
   |                                                              ^^^^^^^

For more information about this error, try `rustc --explain E0432`.
warning: `tun2proxy` (lib) generated 4 warnings
error: could not compile `tun2proxy` due to previous error; 4 warnings emitted

**Comment by yangdehui** [comment]
my rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/yangdehui/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-linux-android
armv7-linux-androideabi
i686-linux-android
x86_64-apple-darwin
x86_64-linux-android

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.69.0 (84c898d65 2023-04-16)

**Comment by blechschmidt** [comment]
macOS is currently not supported.
