### ISSUE TITLE
error[E0412]: cannot find type RawFd in std::os::fd

### ISSUE THREAD

**Issue by foxhacker0000** [blechschmidt/tun2proxy#36]
command:
`sudo cargo build --release`

error:
`   Compiling tun2proxy v0.1.1 (/home/foxhacker/Desktop/vpn/tun2proxy)
error[E0412]: cannot find type `RawFd` in `std::os::fd`
  --> src/lib.rs:24:21
   |
24 |     Fd(std::os::fd::RawFd),
   |                     ^^^^^ not found in `std::os::fd`
   |
help: consider importing this type alias
   |
1  | use std::os::unix::prelude::RawFd;
   |
help: if you import `RawFd`, refer to it directly
   |
24 -     Fd(std::os::fd::RawFd),
24 +     Fd(RawFd),
   |

error[E0603]: module `fd` is private
  --> src/lib.rs:24:17
   |
24 |     Fd(std::os::fd::RawFd),
   |                 ^^ private module
   |
note: the module `fd` is defined here

warning: unused import: `std::os::unix::io::AsRawFd`
  --> src/tun2proxy.rs:20:5
   |
20 | use std::os::unix::io::AsRawFd;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

Some errors have detailed explanations: E0412, E0603.
For more information about an error, try `rustc --explain E0412`.
warning: `tun2proxy` (lib) generated 1 warning
error: could not compile `tun2proxy` due to 2 previous errors; 1 warning emitted
`

**Comment by blechschmidt** [comment]
Does it help if you run `cargo update` before building?

**Comment by foxhacker0000** [comment]
sudo cargo update
error: failed to get `base64` as a dependency of package `tun2proxy v0.1.1 (/home/foxhacker/Desktop/vpn/tun2proxy)`

Caused by:
  failed to load source for dependency `base64`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  usage of sparse registries requires `-Z sparse-registry`

**Comment by foxhacker0000** [comment]
i fixed it

solve:
-Z sparse-registry parameter

sudo cargo update -Z sparse-registry
cargo build --release -Z sparse-registry

**Comment by blechschmidt** [comment]
Great! Closing this.
