### ISSUE TITLE
WSL connection problem

### ISSUE THREAD

**Issue by foxhacker0000** [blechschmidt/tun2proxy#42]
i download compiled version from releases part

tested via root user

sudo ./tun2proxy-x86_64 --setup auto --proxy "socks5://192.168.1.102:0808"

connect but internet will not work

**Comment by blechschmidt** [comment]
`0808` looks like it might be a typo. Apart from that, running tun2proxy on WSL cannot be used to route the traffic of your entire Windows machine through the proxy. It will only be effective on the Linux subsystem at best.

**Comment by foxhacker0000** [comment]
i know but it will not route the traffic of wsl linux distro

this is my problem

**Comment by blechschmidt** [comment]
The executables are quite outdated and I wouldn't use them for testing. I have re-enabled the continuous deployment workflow. The most recent executable is available at https://github.com/blechschmidt/tun2proxy/releases/tag/r6767076a6b3b1126b03dca99ec1df9eb98de9117.

> connect but internet will not work

As I don't have a Windows VM available right now to test it on WSL, I would need some more information. Packet captures of the tunnel and default interfaces would be helpful. Does `curl` work with the proxy on WSL?

**Comment by foxhacker0000** [comment]
curl will not work while tun2proxy in on

**Comment by foxhacker0000** [comment]
i tested again on WSL

on wsl not ping for censored website by Government but in face censored websites will work
it mean cannot get ping via `ping `command in terminal but work in application and browsers

for example telegram.org is censored in Iran and after connect to tun2proxy cannot get ping via `ping `command in terminal
but it will open in browser via ip of proxy :)

**i dont know but work perfectly**

**Comment by blechschmidt** [comment]
I will close this because ping is ICMP on layer 3. There is no straightforward way to enable ping support through SOCKS or HTTP. Some tools may send fake ping replies (which can be perceived by unrealistically low response times), but I don't see the value of such a feature right now. In these cases, the ping reply is generated by the local machine instead of the destination address.
