### ISSUE TITLE
Digest authentication scheme support?

### ISSUE THREAD

**Issue by jorgeajimenezl** [blechschmidt/tun2proxy#43]
Hi, Thanks for the great software, I would like to know if there is any goal to include digest authentication support for HTTP style proxies?

**Comment by blechschmidt** [comment]
Hi and thanks a lot. This project is currently not at the top of my TODO list as there are good alternatives, like [tun2socks](https://github.com/xjasonlyu/tun2socks), and I would prioritize other features such as UDP support, native support for DNS over TCP, and, most importantly, investigating/fixing #32. But I would be happy to accept a PR implementing that feature.

**Comment by jorgeajimenezl** [comment]
Thanks for replying. [tun2socks](https://github.com/xjasonlyu/tun2socks) doesn't have this feature either. I am going to try to implement it here, as I really like the virtual DNS feature so I can use it at my university. I am trying to see how I implement this because I have to see how to re-register the `mio_stream` in the `ConnectionState`, as the proxy may initially close the connection after it is queried to see what schemes it supports (in fact I think that is what it is expected to do). I will see if I can accomplish this without affecting it too much.
