### ISSUE TITLE
UDP timeout errors while using container network

### ISSUE THREAD

**Issue by engageub** [blechschmidt/tun2proxy#73]
Hi,
I tried to use this over container network for IProyals and other containers but UDP timeout errors are occurring.
http proxy is being used. On using BYPASS_IP variable for 8.8.8.8 with DNS on /etc/resolv.conf the system cpu reaches 100%. 
On using -e DNS="direct" , invalid protocols are being logged.
Could you please let me know if direct dns means it makes a direct connection to dns servers instead of going through tun interface. 

Container used: iproyal/pawns-cli:latest

```

Post "https://api.iproyal.com/v1/users/login": dial tcp: lookup api.iproyal.com on 198.18.0.1:53: read udp 172.17.0.7:54692->198.18.0.1:53: i/o timeout
Post "https://api.iproyal.com/v1/users/login": dial tcp: lookup api.iproyal.com on 198.18.0.1:53: read udp 172.17.0.7:47608->198.18.0.1:53: i/o timeout

```

The following are the errors when -e DNS="direct" option is used.

```
[2023-10-28T07:43:06Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:42988 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:06Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:06Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:59830 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:06Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:11Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:34863 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:11Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:11Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:49672 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:11Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:17Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:58003 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:17Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:17Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:54376 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:17Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:22Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:55150 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:22Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:22Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:49256 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:22Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:28Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:52613 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:28Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:28Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:52791 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:28Z ERROR tun2proxy::tun2proxy] Invalid protocol
[2023-10-28T07:43:33Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.7:57018 -> 8.8.8.8:53 (198.18.0.1:53)
[2023-10-28T07:43:33Z ERROR tun2proxy::tun2proxy] Invalid protocol


```

Thank you

**Comment by blechschmidt** [comment]
Unfortunately, direct DNS is currently not supported through Docker as Docker forwards all traffic to tun2proxy, but direct DNS relies on traffic being able to bypass tun2proxy. So you would need to rely on TCP or virtual DNS for the time being. (The `--bypass-ip` argument is only meaningful for the container which tun2proxy is running in and was originally meant to prevent routing loops, for example when using OpenSSH's SOCKS5 implementation which would provide a proxy on localhost but require that the SSH server can be reached without proxy.)

To support direct DNS, tun2proxy would need to pick up the UDP packets and simply forward them to the desired resolver through UDP. This is not too hard to implement, but I currently lack the time to do it, unfortunately.

**Comment by engageub** [comment]
Thank you for your reply.
By Direct DNS, I meant that tun2proxy ignores the port number 53 of the UDP
protocol.
I had the same issue with tun2socks but this was resolved by running ip
rules to ignore port 53 of udp by adding it to the main table.
The same command was not working as iptables is not installed inside the
tun2proxy.
Can it be done similarly in tun2proxy by running commands inside the
container to override the rules.

Could you please explain what it does by adding -e DNS="direct" in docker.
I thought this would route port 53 of UDP from the tun interface to the
default interface.

Thank you

**Comment by blechschmidt** [comment]
Hello again,

when I replied to this thread yesterday, I was in a hurry. Shortly after writing the reply, I realized that it was wrong and therefore deleted it. The reason why it currently does not work is that the `--bypass-ip` is the proxy IP address by default. When specifying a custom `--bypass-ip`, i.e. 8.8.8.8 in your case, this creates a routing loop, because the proxy IP is no longer bypassed. It would, however, work if `--bypass-ip` supported multiple ip addresses.

**Comment by blechschmidt** [comment]
It should work with the `merge-multibypass` branch if you specify 8.8.8.8 and the proxy IP address as `--bypass-ip` addresses. To reduce complexity, CLI args are passed to the entrypoint in the Docker container directly instead of taking the environment variable detour, i.e.:
`docker run -v /dev/net/tun:/dev/net/tun --sysctl net.ipv6.conf.default.disable_ipv6=0 --cap-add NET_ADMIN --name tun2proxy tun2proxy --proxy http://<username>:<passwod>@<proxy_ip>:3128 --dns direct -b 8.8.8.8 -b <proxy_ip>`

Let me know if it works for you. Then it can be merged in the next few days, as soon as the Windows problems with this change are fixed.

**Comment by blechschmidt** [comment]
Merged e08a0f683dd6cb7d5af2fb4c27ab9282992f51e7 into master, which should fix the issue.

**Comment by engageub** [comment]
Hi,
There are few issues here that have to be resolved.
1. Why does iproyals container not work with virtual DNS while curl command (curl https://ifconfig.me)  inside the tun2proxy works fine. This is with respect to the previous version. 
2. Regarding the changes made above, the bypass works with -e DNS="direct" instead of --dns direct option. However iproyals shows new error now and does not work.

```
Post "https://api.iproyal.com/v1/users/login": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

To replicate the issue run the following following commands by replacing with proxy and iproyals username and password.

```
sudo docker run --name tun2proxy --restart=always  -e DNS=direct --sysctl net.ipv6.conf.default.disable_ipv6=0 -v '/dev/net/tun:/dev/net/tun' --cap-add=NET_ADMIN -d ghcr.io/engageub/tun2proxy:master --proxy <PROXY_IP>  -b 8.8.8.8 -b 1.1.1.1
sudo docker exec tun2proxy  sh -c 'echo "nameserver 1.1.1.1" > /etc/resolv.conf;echo "nameserver 8.8.8.8" >> /etc/resolv.conf;'
sudo docker run -d --name pawns --restart=always --network="container:tun2proxy" iproyal/pawns-cli:latest -email=<IP_ROYAL_EMAIL> -password=<IP_ROYAL_PASSWORD> -device-name="ubuntu" -device-id="ubuntu" -accept-tos
```

Thank you

**Comment by blechschmidt** [comment]
0ab52c623b2360dafc8344d6fbad874442929a6b fixes a bug introduced in some refactoring which has caused the virtual DNS feature to not work with all implementations. I tested that the container now works with virtual DNS, i.e. there is no need to use direct DNS.

However, with the latest changes, arguments are no longer passed through the environment, i.e. Docker's `-e`. If you still want to use direct DNS, the above commands now do work when using `sudo docker run --name tun2proxy --restart=always --sysctl net.ipv6.conf.default.disable_ipv6=0 -v '/dev/net/tun:/dev/net/tun' --cap-add=NET_ADMIN -d ghcr.io/engageub/tun2proxy:master --proxy <PROXY_IP>  -b 8.8.8.8 -b 1.1.1.1 --dns direct` instead of passing the DNS mode through `-e`.

**Comment by engageub** [comment]
Hi @blechschmidt ,
Thank you for the response. This resolved the issue with virtual dns. But it does not work with direct dns. Could you please look into it and resolve this as well.

Errors seen while using direct Dns 
```
8d6
Post "https://api.iproyal.com/v1/users/login": dial tcp: lookup api.iproyal.com on 8.8.8.8:53: read udp 172.17.0.4:38121->8.8.8.8:53: i/o timeout
Post "https://api.iproyal.com/v1/users/login": dial tcp: lookup api.iproyal.com on 8.8.8.8:53: read udp 172.17.0.4:36336->8.8.8.8:53: i/o timeout
```

To replicate the issue, please run the following commands

```
sudo docker run --name tun2proxy --restart=always  --sysctl net.ipv6.conf.default.disable_ipv6=0 -v '/dev/net/tun:/dev/net/tun' --cap-add=NET_ADMIN -d ghcr.io/engageub/tun2proxy:master --proxy <PROXY_IP> --dns direct
sudo docker exec tun2proxy  sh -c 'echo "nameserver 1.1.1.1" > /etc/resolv.conf;echo "nameserver 8.8.8.8" >> /etc/resolv.conf;'
sudo docker run -d --name pawns --restart=always --network="container:tun2proxy" iproyal/pawns-cli:latest -email=<IP_ROYAL_EMAIL> -password=<IP_ROYAL_PASSWORD> -device-name="ubuntu" -device-id="ubuntu" -accept-tos
```

**Comment by blechschmidt** [comment]
The first step is
```
docker run -v /dev/net/tun:/dev/net/tun --sysctl net.ipv6.conf.default.disable_ipv6=0 --cap-add NET_ADMIN --name tun2proxy tun2proxy --proxy http://<PROXY_IP>:<PROXY_PORT> --dns direct -b <PROXY_IP> -b 8.8.8.8 -b 1.1.1.1
```

When using the `-b` option, you need to explicity create a route that bypasses the tunnel interface for the proxy IP address itself. (When the `-b` option is not used, a route is created for the proxy IP address automatically.)
You therefore need to ensure that bypass routes for all three IP addresses are created.

**Comment by engageub** [comment]
Hi @blechschmidt ,
Thank you for the response. I do not need -b option as my proxy supports UDP now. 
I want to use DNS through my proxy instead of virtual dns. 
This is required for applications like Mysterium which communicate through UDP apart from DNS queries. 
It looks like IP headers are being validated in pawns app.
If you can resolve this issue, I think mysterium will also work on it. Ongoing issue (https://github.com/xjasonlyu/tun2socks/issues/262)
The tun2proxy logs show the connection but it is not being validated by pawns container. You also need to look into pawns container logs. 

Thank you



Thank you

**Comment by blechschmidt** [comment]
I have updated my response to also include a successful test with UDP through SOCKS5. At least I am getting the following output from the pawns container which indicates that the HTTP request goes through tun2socks:

```
root@tun2proxy-docker-direct-dns:~# docker run -it      --network "container:tun2proxy"         iproyal/pawns-cli:latest -accept-tos
Key: 'Login.Username' Error:Field validation for 'Username' failed on the 'required' tag
Key: 'Login.Password' Error:Field validation for 'Password' failed on the 'required' tag
```

The `/etc/danted.conf` of my test server looks like this:
```
logoutput: /var/log/socks.log
internal: eth0 port = 1080
external: eth0
clientmethod: none
socksmethod: username
user.privileged: root
user.notprivileged: nobody
debug: 1

client pass {
        from: 0/0 to: 0/0
        log: error connect disconnect
}

socks pass {
        from: 0/0 to: 0/0
        command: bind connect udpassociate
        log: error connect disconnect
        socksmethod: username
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    command: bindreply udpreply
}
```

**Comment by engageub** [comment]
It does not seem to be making connection instead validating the input parameters. You have to give email address and password in the environment variables as mentioned in order to request connection . 
Please see the example below.
```
sudo docker run --name tun2proxy --restart=always  --sysctl net.ipv6.conf.default.disable_ipv6=0 -v '/dev/net/tun:/dev/net/tun' --cap-add=NET_ADMIN -d ghcr.io/engageub/tun2proxy:master --proxy <PROXY_IP> --dns direct
sudo docker exec tun2proxy  sh -c 'echo "nameserver 1.1.1.1" > /etc/resolv.conf;echo "nameserver 8.8.8.8" >> /etc/resolv.conf;'
sudo docker run -d --name pawns --restart=always --network="container:tun2proxy" iproyal/pawns-cli:latest -email=<IP_ROYAL_EMAIL> -password=<IP_ROYAL_PASSWORD> -device-name="ubuntu" -device-id="ubuntu" -accept-tos
```

**Comment by blechschmidt** [comment]
In the output I posted above you can see that an HTTPS connection is made to `93.189.62.83:443`, which is the IP address of `api.iproyal.com` after having resolved the DNS through 1.1.1.1. So validation takes place on the server side and UDP is working (for DNS at least).

Otherwise, reverse engineering third-party applications/containers is not within the scope of this project (unless you can specifically pinpoint the issue to an implementation error of tun2proxy).

**Comment by engageub** [comment]
I have setup the dante server with your configuration. But it works only with --dns virtual but not --dns direct.
The log messages that you mentioned for TCP, I see that when virtual dns is used and not direct dns.
Could you please see if you are using latest build as there was an issue with previous build where -e DNS=direct had to be used. The UDP logs are completely different. 


Please find the tun2proxy logs when direct DNS is used. 
My proxy here: socks5://engage:123456@150.230.141.184:1080


```
ubuntu@instance-20230509-2040:~/InternetIncome-main$ sudo docker container logs tun630571ee8e61fb9efaa9786a9de273531
[2023-11-01T12:05:32Z INFO  tun2proxy] Proxy socks5 server: 150.230.141.184:1080
[2023-11-01T12:05:32Z INFO  tun2proxy::setup] [1] Setting up network configuration
[2023-11-01T12:05:33Z WARN  tun2proxy::setup] failed to bind mount custom resolv.conf onto /etc/resolv.conf, resorting to direct write
[2023-11-01T12:05:42Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:49867 -> 1.1.1.1:53 (1.1.1.1:53)
[2023-11-01T12:05:42Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:41669 -> 1.1.1.1:53 (1.1.1.1:53)
[2023-11-01T12:05:42Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:60535 -> 10.0.0.180:57545 (10.0.0.180:57545)
[2023-11-01T12:05:42Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:48555 -> 10.0.0.180:34234 (10.0.0.180:34234)
[2023-11-01T12:05:42Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:35429 -> 10.0.0.180:53411 (10.0.0.180:53411)
[2023-11-01T12:05:42Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:58884 -> 10.0.0.180:42600 (10.0.0.180:42600)
[2023-11-01T12:05:42Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:44156 -> 10.0.0.180:42276 (10.0.0.180:42276)
[2023-11-01T12:05:43Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:40808 -> 10.0.0.180:42978 (10.0.0.180:42978)
[2023-11-01T12:05:43Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:39948 -> 10.0.0.180:36971 (10.0.0.180:36971)
[2023-11-01T12:05:43Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:55903 -> 10.0.0.180:49733 (10.0.0.180:49733)
[2023-11-01T12:05:43Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:57901 -> 10.0.0.180:48795 (10.0.0.180:48795)
[2023-11-01T12:05:43Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:35525 -> 10.0.0.180:38502 (10.0.0.180:38502)
[2023-11-01T12:05:43Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:58338 -> 10.0.0.180:51228 (10.0.0.180:51228)
[2023-11-01T12:05:43Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:56762 -> 10.0.0.180:40314 (10.0.0.180:40314)
[2023-11-01T12:05:43Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:48354 -> 10.0.0.180:53601 (10.0.0.180:53601)
[2023-11-01T12:05:43Z INFO  tun2proxy::tun2proxy] UDP associate session UDP 172.17.0.4:33647 -> 10.0.0.180:44366 (10.0.0.180:44366)

```

IP Royal Pawns logs when direct dns is used
````
Post "https://api.iproyal.com/v1/users/login": dial tcp: lookup api.iproyal.com on 198.18.0.1:53: read udp 172.17.0.7:44829->198.18.0.1:53: i/o timeout

````

**Comment by blechschmidt** [comment]
This is an issue with your proxy, which does not support UDP:
```
12:55:57.367168 eth0  In  IP 150.230.141.184 > 164.92.234.82: ICMP host 150.230.141.184 unreachable - admin prohibited, length 73
```

Something seems to be firewalling UDP. You can verify this using the tool at https://github.com/semigodking/socks5chk:
```
python3 udpchk.py --proxy 150.230.141.184 --user engage --pwd 123456 --port 1080
```

**Comment by engageub** [comment]
Hi,
I enabled ICMP on the host and ping requests are successful.

UDP does not work with the script.

```
ubuntu@instance-20230509-2040:~/socks5chk-master$ python3 udpchk.py --proxy 150.230.141.184 --user engage --pwd 123456 --port 1080
OSError(113, 'No route to host')

```


Even TCP is not working with the script.
```
python3 tcpchk.py --proxy 150.230.141.184 --user engage --pwd 123456 --port 1080
Traceback (most recent call last):
  File "/home/ubuntu/socks5chk-master/tcpchk.py", line 72, in <module>
    main()
  File "/home/ubuntu/socks5chk-master/tcpchk.py", line 68, in main
    test_tcp(None, args.proxy, args.port, args.user, args.pwd)
  File "/home/ubuntu/socks5chk-master/tcpchk.py", line 32, in test_tcp
    req = b"GET / HTTP/1.0\r\nHost: %s\r\n\r\n" % host
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
```

However, curl command works fine. 

```
curl --proxy socks5://engage:123456@150.230.141.184:1080 ifconfig.me
```

Could you please let me know a proxy provider who provides socks5 with UDP support.
I will purchase one and see. 

Thank you

**Comment by blechschmidt** [comment]
> UDP does not work with the script.
> 
> ```
> ubuntu@instance-20230509-2040:~/socks5chk-master$ python3 udpchk.py --proxy 150.230.141.184 --user engage --pwd 123456 --port 1080
> OSError(113, 'No route to host')
> ```

What you seeing here is the error generated by the OS

> 
> Even TCP is not working with the script.
> 
> ```
> python3 tcpchk.py --proxy 150.230.141.184 --user engage --pwd 123456 --port 1080
> Traceback (most recent call last):
>   File "/home/ubuntu/socks5chk-master/tcpchk.py", line 72, in <module>
>     main()
>   File "/home/ubuntu/socks5chk-master/tcpchk.py", line 68, in main
>     test_tcp(None, args.proxy, args.port, args.user, args.pwd)
>   File "/home/ubuntu/socks5chk-master/tcpchk.py", line 32, in test_tcp
>     req = b"GET / HTTP/1.0\r\nHost: %s\r\n\r\n" % host
> TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
> ```

Looks like the `tcp.py` script only supports Python 2, but the TCP check is irrelevant as we know that this works.

> Could you please let me know a proxy provider who provides socks5 with UDP support. I will purchase one and see.

I'd recommend setting up Dante on a DigitalOcean VPS.

**Comment by engageub** [comment]
Hi @blechschmidt,

Thank you for the response. I got trial proxies for 1 day and it is working for iproyals now. However, it does not work with mysterium.

Proxy Used: socks5://engageaffli:9B16F7CD3C9D1761F0D5FE822C96C9A3@191.96.246.161:23100

Mysterium Website link: https://mystnodes.com/

Please find the mysterium log errors.

```
2023-11-01T16:27:00.724 ERR ../../core/ip/resolver.go:102                  > could not reach location service, will use fallbacks error="Get \"https://location.mysterium.network/api/v1/location\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
2023-11-01T16:27:00.725 WRN ../../core/location/cache.go:129               > Failed to detect original location error="failed to execute request: Get \"https://location.mysterium.network/api/v1/location\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

```


Thank you

**Comment by blechschmidt** [comment]
Please first rule out that your issue is proxy-specific (e.g. Mysterium banning your proxies). The pro of using a VPS would be that you could set up Docker there and first test the container on the VPS without tun2proxy. This allows you to rule out that this is some proxy-specific problem like firewalling or IP reputation. If it works on the VPS, you install danted there. Now you use that same VPS as a proxy with tun2proxy on some different machine.

**Comment by engageub** [comment]
> Please first rule out that your issue is proxy-specific (e.g. Mysterium banning your proxies). The pro of using a VPS would be that you could set up Docker there and first test the container on the VPS without tun2proxy. This allows you to rule out that this is some proxy-specific problem like firewalling or IP reputation. If it works on the VPS, you install danted there. Now you use that same VPS as a proxy with tun2proxy on some different machine.

Mysterium allows both residential and datacenter proxies. It works fine with direct connection on VPS but not with tun2proxy.  Timeouts waiting for client headers is appearing in between when using with tun2proxy where as with direct connection it does not happen.  Due to these errors, the device shows online but no earnings are possible.
Could you please look into this.

**Comment by blechschmidt** [comment]
The install instructions of Mysterium read that `it's mandatory to run docker container with --net host to correctly detect VPN service ip which needs to be published to clients, assuming that host on which node is running has external interface with public ip` (https://github.com/mysteriumnetwork/node/blob/master/INSTALL.md)
If this applies to all use cases, Mysterium is inherently incompatible with solutions like tun2proxy as these do not allow for this kind of IP address discovery (the interfaces Mysterium will see are those of the tun2proxy container) and do not support publishing services (because they purely operate at the network layer, they don't see when a socket is opened at the OS layer and do not support UPnP for port mappings).
