### ISSUE TITLE
[Feature Request] Package for docker

### ISSUE THREAD

**Issue by engageub** [blechschmidt/tun2proxy#76]
Hi @blechschmidt ,

Could you please publish package for this.
I currently forked the branch and am using published version for docker.
I would like to use it from main source instead of forked source. 

Link for docker package being used: https://github.com/engageub/tun2proxy/pkgs/container/tun2proxy 

Thank you

**Comment by blechschmidt** [comment]
See https://github.com/blechschmidt/tun2proxy/pkgs/container/tun2proxy.

**Comment by engageub** [comment]
Hi @blechschmidt,

Could you please update the packages for docker to the latest version.
Many changes have been made to the code since it was published.


Thank you

**Comment by blechschmidt** [comment]
The image should be generated when the next tag is pushed.
