### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by zengyuxing007** [blechschmidt/tun2proxy#94]
cargo build --release
    Updating crates.io index
error: failed to select a version for `env_logger`.
    ... required by package `tun2proxy v0.2.10 (/root/Work/tun2proxy)`
versions that meet the requirements `^0.11` are: 0.11.2, 0.11.1, 0.11.0
the package `tun2proxy` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
failed to select a version for `env_logger` which could resolve this conflict

**Comment by harismuzaffer** [comment]
This is fixed in Rust 1.72. https://github.com/rust-lang/cargo/issues/10788

**Comment by zengyuxing007** [comment]
> This is fixed in Rust 1.72. [rust-lang/cargo#10788](https://github.com/rust-lang/cargo/issues/10788)

thanks ~
