### ISSUE TITLE
How to allow only the routes on a specified network segment to pass through the proxy? For example, using tun2proxy as a vpn mode?

### ISSUE THREAD

**Issue by masx200** [blechschmidt/tun2proxy#96]
How to allow only the routes on a specified network segment to pass through the proxy? For example, using tun2proxy as a vpn mode?

**Comment by ssrlive** [comment]
Currently tun2proxy is not supported for specifying the network segment to be bypass with CIDR.
Single target IP is supported. Please check the [wiki](https://github.com/blechschmidt/tun2proxy/wiki).

**Comment by blechschmidt** [comment]
It's not supported through `--setup` currently, but it can be done manually by employing the steps from the README file and only adding the desired route to the tunnel interface instead of 0.0.0.0/0 or 0.0.0.0/1 and 128.0.0.0/1.
